AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 instance using parameters.

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.micro
      - t2.large
    Description: Select EC2 instance type

Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-97785bed                             # Replace with your Amazon Linux AMI ID
      InstanceType: !Ref InstanceTypeParameter