AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 instance using parameter type keypair.

Parameters:
  InstanceTypeParameter:
    Type: String
    AllowedValues:
      - t2.micro
      - t2.micro
      - t2.large
    Description: Select EC2 instance type
  myportNumber:
    Type: Number
    Defualt: 1
    Description: Enter Port Number
  EC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 key pair
  myAZParameter:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Select AZ
  myAmiID:
    Type: AWS::EC2::Image::Id
    Description: Enter AMI ID

Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-97785bed                             # Replace with your Amazon Linux AMI ID
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref EC2KeyPair