AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 instance with custom Security group using import function.


Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-97785bed                               # Replace with your Amazon Linux AMI ID
      InstanceType: t2.micro
      SubnetId: subnet-2a4e2326
      SecurityGroupIds:
        - Fn::ImportValue: My6aSG
